/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class RemoteFrm extends javax.swing.JFrame {

    /**
     * Creates new form RemoteFrm
     */
    public RemoteFrm() {
        initComponents();
    }

    public void setScreen(byte[] content) {
        try {
            ImageIcon image = new ImageIcon(content);
            resize(image.getIconWidth(), image.getIconHeight());
            lblFrm.resize(image.getIconWidth(), image.getIconHeight());
            lblFrm.setIcon(image);
        } catch (Exception ex) {
            System.out.println("Lỗi set ảnh" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void KeyActionListener(KeyListener act){
        this.lblFrm.addKeyListener(act);
    }
    public void MouseActionListener(MouseListener act){
        this.lblFrm.addMouseListener(act);
    }
    public void MouseWheelListener(MouseWheelListener act){
        this.lblFrm.addMouseWheelListener(act);
    }
    public void MouseMotionListener(MouseMotionListener act){
        this.lblFrm.addMouseMotionListener(act);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lblFrm);
        lblFrm.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFrm;
    // End of variables declaration//GEN-END:variables
}
